CREATE TABLE PERSONA
(
  IDPERSONA INTEGER PRIMARY KEY  NOT NULL 
            GENERATED ALWAYS AS IDENTITY 
            (START WITH 1, INCREMENT   BY 1),
  NOMBRE VARCHAR(30) NOT NULL,
  FECHANAC   Date,
  SEXO   CHAR,
ESTATURA INT

);

CREATE TABLE MEDICIONES
(
 IDMEDIDAS INTEGER PRIMARY KEY NOT NULL 
    GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 FECHA Date,
 PESO DOUBLE,
 CINTURA   INT,
 CADERA    INT,
 IDTIPOACT INT REFERENCES TIPOACTIUIDAD(IDTIPOACT), 
 IDPERSONA INT REFERENCES PERSONA (IDPERSONA) 
);

CREATE TABLE TIPOACTIUIDAD
(IDTIPOACT INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOMBRE  VARCHAR(30) NOT NULL,
DESCRIPCION  VARCHAR(40) NOT NULL
);
